TASK 1

In [8]:
import numpy as np
import time

arr1 = np.arange(1, 11)
print(arr1)

[ 1  2  3  4  5  6  7  8  9 10]


TASK 2


In [9]:
arr2 = arr1.astype('float32')
print(arr2, "| dtype:", arr2.dtype)

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.] | dtype: float32


TASK 3

In [10]:
exponents = np.arange(2, 17)
arr3 = 2 ** exponents
print(arr3)

[    4     8    16    32    64   128   256   512  1024  2048  4096  8192
 16384 32768 65536]


TASK 4

In [11]:
matrix = np.arange(1, 26).reshape(5, 5)
print("Full Matrix:\n", matrix)
print("Last value:", matrix[-1, -1])
print("Second column:", matrix[:, 1])
print("Third row:", matrix[2, :])
print("Main diagonal:", np.diag(matrix))
print("Sub-matrix (9,10,14,15):\n", matrix[1:3, 3:5])

Full Matrix:
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
Last value: 25
Second column: [ 2  7 12 17 22]
Third row: [11 12 13 14 15]
Main diagonal: [ 1  7 13 19 25]
Sub-matrix (9,10,14,15):
 [[ 9 10]
 [14 15]]


TASK 5

In [12]:
cube = np.arange(1, 28).reshape(3, 3, 3)
print("Elements where y=1 (vertical axis index 1):\n", cube[:, 1, :])
print("Values for z=0 and z=2 (depth indices - NumPy 0-indexed):\n", cube[:, :, [0, 2]])

Elements where y=1 (vertical axis index 1):
 [[ 4  5  6]
 [13 14 15]
 [22 23 24]]
Values for z=0 and z=2 (depth indices - NumPy 0-indexed):
 [[[ 1  3]
  [ 4  6]
  [ 7  9]]

 [[10 12]
  [13 15]
  [16 18]]

 [[19 21]
  [22 24]
  [25 27]]]


TASK 6

In [13]:
n = 10000

# Case A
start = time.time()
lst = list(range(n))
res_a = []
for x in lst:
    res_a.append(x * 2)
print(f"List for loop time: {time.time() - start:.6f}s")

# Case B
start = time.time()
res_b = [x * 2 for x in lst]
print(f"List comprehension time: {time.time() - start:.6f}s")

# Case C
start = time.time()
np_arr = np.arange(n)
res_c = np_arr * 2
print(f"NumPy array time: {time.time() - start:.6f}s")

List for loop time: 0.000788s
List comprehension time: 0.000343s
NumPy array time: 0.000284s
