TASK 1 & 2

In [1]:
import numpy as np
matrix = np.arange(2, 34, 2).reshape(4, 4)

print("Original Matrix:")
print(matrix)
print(f"Dtype: {matrix.dtype}")
print(f"Elements: {matrix.size}")
print(f"Item size: {matrix.itemsize}")
print(f"Total memory: {matrix.nbytes} bytes")

print("-" * 30)

view_uint8 = matrix.view().astype('uint8')
is_view = view_uint8.base is matrix

print("Uint8 Matrix:")
print(view_uint8)
print(f"Is view: {is_view}")
print(f"Elements: {view_uint8.size}")
print(f"Item size: {view_uint8.itemsize}")
print(f"Total memory: {view_uint8.nbytes} bytes")

Original Matrix:
[[ 2  4  6  8]
 [10 12 14 16]
 [18 20 22 24]
 [26 28 30 32]]
Dtype: int64
Elements: 16
Item size: 8
Total memory: 128 bytes
------------------------------
Uint8 Matrix:
[[ 2  4  6  8]
 [10 12 14 16]
 [18 20 22 24]
 [26 28 30 32]]
Is view: False
Elements: 16
Item size: 1
Total memory: 16 bytes


TASK 3 

In [2]:
center_view = matrix[1:3, 1:3]
center_copy = matrix[1:3, 1:3].copy()

print("Center view values:\n", center_view)
print("Base of view:", center_view.base if center_view.base is not None else "None")
print("Base of copy:", center_copy.base if center_copy.base is not None else "None")
print(f"Bases are different: {center_view.base is not center_copy.base}")

Center view values:
 [[12 14]
 [20 22]]
Base of view: [ 2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32]
Base of copy: None
Bases are different: True


TASK 4 

In [3]:
row = np.array([1, 2, 3, 4])
base_matrix = np.tile(row, (4, 1))

mirror = base_matrix[:, ::-1]

final_concat = np.concatenate((base_matrix, mirror), axis=1)

print("Row structure after concatenation:")
print(final_concat[0])
print("\nFull mirrored matrix:")
print(final_concat)

Row structure after concatenation:
[1 2 3 4 4 3 2 1]

Full mirrored matrix:
[[1 2 3 4 4 3 2 1]
 [1 2 3 4 4 3 2 1]
 [1 2 3 4 4 3 2 1]
 [1 2 3 4 4 3 2 1]]


TASK 5 

In [4]:
z_5 = np.ones((2, 2), dtype=int)

top = np.concatenate((z_5, z_5 * 2), axis=1)
bottom = np.concatenate((z_5 * 3, z_5 * 4), axis=1)

block_matrix = np.concatenate((top, bottom), axis=0)

print("Block assembled matrix:")
print(block_matrix)

Block assembled matrix:
[[1 1 2 2]
 [1 1 2 2]
 [3 3 4 4]
 [3 3 4 4]]


TASK 6

In [5]:
a_small_one = np.arange(1, 65).reshape(8, 8).astype(float)

no_even_small_one = np.where(a_small_one % 2 == 0, np.nan, a_small_one)

no_even_small_one = np.where(np.isnan(no_even_small_one), 1, no_even_small_one)

restored_array = np.where(a_small_one % 2 == 0, a_small_one, no_even_small_one)

print("Restored Array (Original state):")
print(restored_array)

Restored Array (Original state):
[[ 1.  2.  3.  4.  5.  6.  7.  8.]
 [ 9. 10. 11. 12. 13. 14. 15. 16.]
 [17. 18. 19. 20. 21. 22. 23. 24.]
 [25. 26. 27. 28. 29. 30. 31. 32.]
 [33. 34. 35. 36. 37. 38. 39. 40.]
 [41. 42. 43. 44. 45. 46. 47. 48.]
 [49. 50. 51. 52. 53. 54. 55. 56.]
 [57. 58. 59. 60. 61. 62. 63. 64.]]


TASK 7 & 8

In [6]:
normal_100 = np.random.standard_normal((100, 100))

row_means = np.mean(normal_100, axis=1)
col_means = np.mean(normal_100, axis=0)

row_abs_diff = np.mean(np.abs(normal_100 - 0), axis=1)
col_abs_diff = np.mean(np.abs(normal_100 - 0), axis=0)

print(f"Mean of first 5 rows: {row_means[:5]}")
print(f"Average absolute difference (first 5 columns): {col_abs_diff[:5]}")

Mean of first 5 rows: [-0.03248165  0.0572331  -0.02931172 -0.11313044 -0.15727385]
Average absolute difference (first 5 columns): [0.72767961 0.6767765  0.77324152 0.85765167 0.78617832]


TASK 9

In [7]:
import time

large_array = np.random.standard_normal((1000, 1000))

start = time.time()
np.savetxt('data.txt', large_array)
txt_write = time.time() - start

start = time.time()
np.savez_compressed('data.npz', large_array)
comp_write = time.time() - start

start = time.time()
np.save('data.npy', large_array)
npy_write = time.time() - start

print(f"Write times: \nTXT: {txt_write:.4f}s \nNPZ: {comp_write:.4f}s \nNPY: {npy_write:.4f}s")

start = time.time()
loaded_txt = np.loadtxt('data.txt')
txt_read = time.time() - start

print(f"\nRead time (Text): {txt_read:.4f}s")

Write times: 
TXT: 0.5921s 
NPZ: 0.3124s 
NPY: 0.0041s

Read time (Text): 0.3856s
