TASK 1

In [2]:
import numpy as np
arr1 = np.arange(2, 33, 2).reshape(4, 4)

print("Matrix:\n", arr1)
print("Data Type:", arr1.dtype)
print("Number of elements:", arr1.size)
print("Size of a single element (bytes):", arr1.itemsize)
print("Total memory allocated (bytes):", arr1.nbytes)

Matrix:
 [[ 2  4  6  8]
 [10 12 14 16]
 [18 20 22 24]
 [26 28 30 32]]
Data Type: int64
Number of elements: 16
Size of a single element (bytes): 8
Total memory allocated (bytes): 128


TASK 2

In [3]:
arr2 = arr1.view().astype('uint8')

is_view = arr2.base is arr1

print("Uint8 Matrix:\n", arr2)
print("Is it a view of arr1?", is_view)
print("Number of elements:", arr2.size)
print("Size of a single element:", arr2.itemsize)
print("Total memory:", arr2.nbytes)

Uint8 Matrix:
 [[ 2  4  6  8]
 [10 12 14 16]
 [18 20 22 24]
 [26 28 30 32]]
Is it a view of arr1? False
Number of elements: 16
Size of a single element: 1
Total memory: 16


TASK 3 

In [4]:
view_center = arr1[1:3, 1:3]

copy_center = arr1[1:3, 1:3].copy()

print("Center values:\n", view_center)
print("Bases are different?", view_center.base is not copy_center.base)

Center values:
 [[12 14]
 [20 22]]
Bases are different? True


TASK 4 

In [5]:

base_row = np.array([1, 2, 3, 4])
matrix_4x4 = np.tile(base_row, (4, 1))

mirror_matrix = matrix_4x4[:, ::-1]

final_matrix = np.concatenate((matrix_4x4, mirror_matrix), axis=1)

print("First row of concatenated matrix:\n", final_matrix[0])
print("Full Concatenated Matrix:\n", final_matrix)

First row of concatenated matrix:
 [1 2 3 4 4 3 2 1]
Full Concatenated Matrix:
 [[1 2 3 4 4 3 2 1]
 [1 2 3 4 4 3 2 1]
 [1 2 3 4 4 3 2 1]
 [1 2 3 4 4 3 2 1]]


TASK 5

In [6]:
z_5 = np.ones((2, 2), dtype=int)

top_half = np.concatenate((z_5, z_5 * 2), axis=1)  
bottom_half = np.concatenate((z_5 * 3, z_5 * 4), axis=1) 
final_4x4 = np.concatenate((top_half, bottom_half), axis=0)

print("Final 4x4 Matrix:\n", final_4x4)

Final 4x4 Matrix:
 [[1 1 2 2]
 [1 1 2 2]
 [3 3 4 4]
 [3 3 4 4]]
